### ISSUE TITLE
(Bug) wrong result when undefined key present

### ISSUE THREAD

**Issue by krishan** [mjackson/value-equal#5]
`valueEqual` falsely considers these two objects to be equal:

`valueEqual({ foo: undefined }, { bar: 1 })`

Expected:

`false`

Actual: 

`true`

**Comment by krishan** [comment]
Thanks for fixing this 👍

One thing I noticed though - doing two comparisons is not necessary and impacts performance. Performance may now become exponential at worst for deeply nested objects. AFAICS ‘valueEqual(a[key], b[key])’ should be sufficient. 

https://github.com/mjackson/value-equal/blob/06d15ef075ddbeaa59e52c7f7c241acaebd7d708/modules/index.js#L34

**Comment by mjackson** [comment]
Agree, @krishan. I noticed the same thing and fixed it in https://github.com/mjackson/value-equal/commit/1761c2e71a24f52c7aaeed93e43234aecce6f807. 😅
